language: python
python: 
 - "3.4"
 - "3.5"
 - "3.6"
sudo: false

env:
  - TOXENV=check
  - TOXENV=py3.6-django1.11
  - TOXENV=py3.5-django1.11
  - TOXENV=py3.4-django1.11
  - TOXENV=py3.5-django1.10
  - TOXENV=py3.4-django1.10
  - TOXENV=py3.5-django1.9
  - TOXENV=py3.4-django1.9
  - TOXENV=py3.5-django1.8
  - TOXENV=py3.4-django1.8
  - TOXENV=py3.3-django1.8
  - TOXENV=py3.6-djangomaster
  - TOXENV=py3.5-djangomaster
  - TOXENV=py3.4-djangomaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py3.6-djangomaster
    - env: TOXENV=py3.5-djangomaster
    - env: TOXENV=py3.4-djangomaster

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - pip install tox

script:
  - tox -v

after_success:
  - coveralls
